language: node_js
node_js: 
  - "8.6.0"
branches:
    only:
        - master
before_script:
    - npm install -g --silent firebase-tools # installs firebase to run firebase deploy
script:
    - echo "Deploying!"
after success:
    - firebase deploy --token $firebaseTokenDW --non-interactive