language: node_js
node_js:
  - "8.6.0"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
deploy:
  provider: firebase
  token:
   secure: $FIRBASE_TOKEN